import type { Metadata } from "next";
import { Inter, Roboto, Jomhuria } from "next/font/google";
import "./globals.css";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin", "latin-ext"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  /**  icons: {
    icon: [
      {
        media: "(prefers-color-scheme: light)",
        url: "public/images/favicon.ico",
        href: "public/images/favicon.ico",
        //src/public/assets/images/favicon.ico
      },

       * {
        media: "(prefers-color-scheme: dark)",
        url: "/images/icon.png",
        href: "/images/icon-dark.png",
      },
       
    ],
  },*/
};

export const jomhuria = Jomhuria({
  subsets: ["latin"],
  weight: "400",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="es"
      className=" text-slate-900 bg-background-color h-screen w-full m-0 p-0"
    >
      <head>
        <link rel="icon" href="src/app/favicon.ico" sizes="32x32" />
      </head>
      <body className={roboto.className}>
        <main>{children}</main>
      </body>
    </html>
  );
}
